name: Hello world
on: workflow_dispatch
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Build Step
         run: echo "The Build step"
  test:
     runs-on: ubuntu-latest
     steps:
       - name: Test phase
         run: echo "Running test cases"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        run: echo "Deploying the App"
        
    
  
        
  
  

     
      
  

  

       

       
       
         
