name: Hello world
on: workflow_dispatch
jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
       - name: Hello step
         run: |
           echo "This is the line one"
           echo "This is the line two"
         
